# Generated by Django 2.1.7 on 2019-03-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUTUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_us', models.CharField(max_length=2000)),
                ('Aim', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=2000)),
                ('Image', models.CharField(max_length=100)),
                ('Developer', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AGGREGATED_DATA',
            fields=[
                ('agd_id', models.AutoField(primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=10000)),
                ('html_content', models.TextField()),
                ('institute_name', models.CharField(max_length=10000)),
                ('article_heading', models.CharField(max_length=10000)),
                ('pdf_links', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ANSWERS',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100000)),
                ('question_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=100000)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('reports', models.IntegerField()),
                ('tags', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='ARTICLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_no', models.CharField(max_length=20)),
                ('Heading', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=4000)),
                ('User', models.CharField(max_length=100)),
                ('Time_date', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=10000)),
                ('image1_link', models.CharField(max_length=10000)),
                ('contents', models.CharField(default='SOME STRING', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('answer_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=100000)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('reports', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FOOTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disclaimer', models.CharField(max_length=2000)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Facebook', models.CharField(max_length=50)),
                ('Twitter', models.CharField(max_length=50)),
                ('Google', models.CharField(max_length=50)),
                ('Instagram', models.CharField(max_length=50)),
                ('Terms', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HEAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_link', models.CharField(max_length=200)),
                ('Login_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HOME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=200)),
                ('Caption', models.CharField(max_length=500)),
                ('Back_img', models.CharField(max_length=200)),
                ('Curosal1', models.CharField(max_length=200)),
                ('Curosal2', models.CharField(max_length=200)),
                ('News_title', models.CharField(max_length=200)),
                ('News_img', models.CharField(max_length=200)),
                ('News_des', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=10000)),
                ('image1_link', models.CharField(max_length=10000)),
                ('contents', models.CharField(default='SOME STRING', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='QUESTIONS',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100000)),
                ('description', models.CharField(max_length=100000)),
                ('likes', models.IntegerField()),
                ('categories', models.CharField(max_length=100000)),
                ('user_email', models.CharField(max_length=100000)),
                ('dislikes', models.IntegerField()),
                ('reports', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='REGISTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
                ('Institution', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('OTP', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', models.CharField(max_length=10000)),
                ('slider_caption', models.CharField(max_length=10000)),
                ('image_link', models.CharField(max_length=10000)),
            ],
        ),
    ]
