# Generated by Django 2.1.7 on 2019-03-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregated_data',
            name='html_content',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='aggregated_data',
            name='pdf_links',
            field=models.CharField(default='None', max_length=10000),
        ),
    ]
